export const search = (text) => {
    return {
        type: CONSTANTS.SEARCH,
        payload: {
            text
        }
    }
}

export const setPageName = (text) => {
    return {
        type: CONSTANTS.PAGENAME,
        payload: {
            text
        }
    }
}

export const CONSTANTS = {
    FETCH_CARDS_PENDING : 'FETCH_CARDS_PENDING',
    FETCH_CARDS_SUCCESS : 'FETCH_CARDS_SUCCESS',
    FETCH_CARDS_FAILURE : 'FETCH_CARDS_FAILURE',
    ADD_CARD_PENDING: "ADD_CARD_PENDING",
    ADD_CARD_SUCCESS: "ADD_CARD_SUCCESS",
    ADD_CARD_FAILURE: "ADD_CARD_FAILURE",
    UPDATE_CARD_PENDING: "UPDATE_CARD_PENDING",
    UPDATE_CARD_SUCCESS: "UPDATE_CARD_SUCCESS",
    UPDATE_CARD_FAILURE: "UPDATE_CARD_FAILURE",
    DELETE_CARD_PENDING: "DELETE_CARD_PENDING",
    DELETE_CARD_SUCCESS: "DELETE_CARD_SUCCESS",
    DELETE_CARD_FAILURE: "DELETE_CARD_FAILURE",
    SORT_CARD_PENDING: "SORT_CARD_PENDING",
    SORT_CARD_SUCCESS: "SORT_CARD_SUCCESS",
    SORT_CARD_FAILURE: "SORT_CARD_FAILURE",
    UPDATE_CARD_UI_IMMEDIATE: "UPDATE_CARD_UI_IMMEDIATE",
    FETCH_LISTS_PENDING : 'FETCH_LISTS_PENDING',
    FETCH_LISTS_SUCCESS : 'FETCH_LISTS_SUCCESS',
    FETCH_LISTS_FAILURE : 'FETCH_LISTS_FAILURE',
    ADD_LIST_PENDING: "ADD_LIST_PENDING",
    ADD_LIST_SUCCESS: "ADD_LIST_SUCCESS",
    ADD_LIST_FAILURE: "ADD_LIST_FAILURE",
    UPDATE_LIST_PENDING: "UPDATE_LIST_PENDING",
    UPDATE_LIST_SUCCESS: "UPDATE_LIST_SUCCESS",
    UPDATE_LIST_FAILURE: "UPDATE_LIST_FAILURE",
    DELETE_LIST_PENDING: "DELETE_LIST_PENDING",
    DELETE_LIST_SUCCESS: "DELETE_LIST_SUCCESS",
    DELETE_LIST_FAILURE: "DELETE_LIST_FAILURE",
    SORT_LIST_PENDING: "SORT_LIST_PENDING",
    SORT_LIST_SUCCESS: "SORT_LIST_SUCCESS",
    SORT_LIST_FAILURE: "SORT_LIST_FAILURE",
    UPDATE_LIST_UI_IMMEDIATE: "UPDATE_LIST_UI_IMMEDIATE",
    FETCH_BOARDS_PENDING : 'FETCH_BOARDS_PENDING',
    FETCH_BOARDS_SUCCESS : 'FETCH_BOARDS_SUCCESS',
    FETCH_BOARDS_FAILURE : 'FETCH_BOARDS_FAILURE',
    ADD_BOARD_PENDING: "ADD_BOARD_PENDING",
    ADD_BOARD_SUCCESS: "ADD_BOARD_SUCCESS",
    ADD_BOARD_FAILURE: "ADD_BOARD_FAILURE",
    UPDATE_BOARD_PENDING: "UPDATE_BOARD_PENDING",
    UPDATE_BOARD_SUCCESS: "UPDATE_BOARD_SUCCESS",
    UPDATE_BOARD_FAILURE: "UPDATE_BOARD_FAILURE",
    DELETE_BOARD_PENDING: "DELETE_BOARD_PENDING",
    DELETE_BOARD_SUCCESS: "DELETE_BOARD_SUCCESS",
    DELETE_BOARD_FAILURE: "DELETE_BOARD_FAILURE",
    SORT_BOARD_PENDING: "SORT_BOARD_PENDING",
    SORT_BOARD_SUCCESS: "SORT_BOARD_SUCCESS",
    SORT_BOARD_FAILURE: "SORT_BOARD_FAILURE",
    UPDATE_BOARD_UI_IMMEDIATE: "UPDATE_BOARD_UI_IMMEDIATE",
    SET_CURRENT_BOARDID: "SET_CURRENT_BOARDID",
    SEARCH: "SEARCH",
    PAGENAME: "PAGENAME"
};

export const alertConstants = {
    SUCCESS: 'ALERT_SUCCESS',
    ERROR: 'ALERT_ERROR',
    CLEAR: 'ALERT_CLEAR'
};

export const userConstants = {
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    LOGOUT: 'USERS_LOGOUT',

    GETALL_REQUEST: 'USERS_GETALL_REQUEST',
    GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
    GETALL_FAILURE: 'USERS_GETALL_FAILURE',

    SIGNUP_REQUEST: 'USERS_SIGNUP_REQUEST',
    SIGNUP_SUCCESS: 'USERS_SIGNUP_SUCCESS',
    SIGNUP_FAILURE: 'USERS_SIGNUP_FAILURE',
};